name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install joblib pytest

    - name: Lint code
      run: |
        pylint M1/model.py M1/test_model.py

    - name: Run tests
      run: |
        pytest M1/test_model.py

    - name: Deploy model
      run: |
        # Deployment steps (e.g., upload to cloud storage)
        echo "Deploying model..."
